on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run:  actions/checkout@v4

	  - name: Setup Go
	    run:  actions/setup-go@v5
	    with:
	      go-version: "1.22"

      - name: Build Go Binary
        run: ./scrips/buildprod.sh
